/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import conexion.Conexion;
import entidades.Contrato;
import entidades.CuotaImpuesto;
import entidades.Cuotas;
import entidades.Impuesto;
import gestores.GestoresContrato;
import gestores.GestoresImpuestos;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static pantallas.ImpuestoCompartido.lblIdImpuestoCompartido;
import static pantallas.LiquidacionInquilino.lblPeriodo;

/**
 *
 * @author Nahuel
 */
public class AgregarImpuestoCuota extends javax.swing.JFrame {

    /**
     * Creates new form AgregarImpuestos
     */
    public AgregarImpuestoCuota() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboImpuestos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        importeImpuesto = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        idPeriodo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Impuesto");
        setIconImage(getIconImage());
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jButton1.setText("Finalizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Impuesto: ");

        comboImpuestos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        comboImpuestos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboImpuestosItemStateChanged(evt);
            }
        });
        comboImpuestos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboImpuestosMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Importe:");

        importeImpuesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                importeImpuestoKeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        idPeriodo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(idPeriodo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idPeriodo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("$");

        lblCom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboImpuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(importeImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCom, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(lblCom))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importeImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboImpuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

        String sql="SELECT * FROM `descripcionimpuesto` ORDER BY `idDescripcion` ASC";
        ResultSet rs=null;
        try{
            PreparedStatement pst=Conexion.getConexionn().prepareStatement(sql);
            rs=pst.executeQuery();
            
            while(rs.next()){
                comboImpuestos.addItem(rs.getString("idDescripcion")+" - "+rs.getString("descripcion"));
            }
            
            
        }catch (SQLException e) {
			JOptionPane.showMessageDialog(new JDialog(),"Error al consultar Impuesto"+e.toString());
        }
        


        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  
        String descripcion=(String) comboImpuestos.getSelectedItem();
        if ((Integer.parseInt(descripcion.substring(0,(descripcion.indexOf("-")-1)))) == 0){
            JOptionPane.showMessageDialog(new JDialog(),"Seleccione un impuesto");
        }else{
            try{
            int r=0;  
            String sql2="SELECT * FROM `impuesto`ORDER BY idImpuesto DESC LIMIT 1";
            ResultSet rs2=null;
            try{
                PreparedStatement pst2=Conexion.getConexionn().prepareStatement(sql2);
                rs2=pst2.executeQuery();            
                while(rs2.next()){
                     idImpuesto=Integer.parseInt(rs2.getString("idImpuesto"))+1;
                }
            }catch (SQLException e) {
                JOptionPane.showMessageDialog(new JDialog(),"Error al consultar Impuesto"+e.toString());
            }



            Contrato contrato=new Contrato();
            Cuotas cuotas=new Cuotas();
            CuotaImpuesto cuotaImp=new CuotaImpuesto();
            Impuesto impuesto=new Impuesto();
            contrato.setIdContrato(Integer.parseInt(idPeriodo.getText().substring(0, idPeriodo.getText().indexOf("-")-1)));
            cuotas.setContrato(contrato);
            cuotas.setNroCuota(nroCuota);        
            impuesto.setIdImpuesto(idImpuesto);
            impuesto.setIdDescripcion(Integer.parseInt(descripcion.substring(0,(descripcion.indexOf("-")-1))));
            impuesto.setValor(Double.parseDouble(importeImpuesto.getText()));
 //         impuesto.setIdImpuestoCompartido(Integer.parseInt(" "));
            cuotaImp.setCuotas(cuotas);
            cuotaImp.setImpuesto(impuesto);
            int idcon=(Integer.parseInt(idPeriodo.getText().substring(0, idPeriodo.getText().indexOf("-")-1)));
            int iddes=(Integer.parseInt(descripcion.substring(0,(descripcion.indexOf("-")-1))));
            try {
                lblCom.setText(GestoresImpuestos.TraerImpuestoCompartido(idcon, iddes));
            } catch (SQLException ex) {
                Logger.getLogger(DetallesContrato.class.getName()).log(Level.SEVERE, null, ex);
            }    
            if(lblCom.getText().isEmpty()){
                GestoresImpuestos gestorImp=new GestoresImpuestos();
                GestoresContrato gestorCon=new GestoresContrato();
                r=gestorImp.GestorAltaImpuesto(cuotaImp);
                try {
                    int rr=gestorImp.ActualizarTotalImpuesto(cuotaImp.getCuotas().getContrato().getIdContrato(), nroCuota);

                    int actualizarTotal=gestorCon.ActualizarTotalaPagar(cuotaImp.getCuotas().getContrato().getIdContrato(), nroCuota);
                } catch (SQLException ex) {
                    Logger.getLogger(AgregarImpuestoCuota.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else{
                  Object[] opciones = {"Cargar impuesto compartido", "Cancelar"};
                int eleccion = JOptionPane.showOptionDialog(null, "El impuesto "+ descripcion+ " es compartido","Mensaje de Confirmacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE, null, opciones, "Cancelar");
                if (eleccion == JOptionPane.YES_OPTION) {
                    int x=GestoresImpuestos.ultimoIdImpuestoCompartido()+1;
                    String idImp= Integer.toString(x);
                    ImpuestoCompartido impcom = new ImpuestoCompartido();
                    ImpuestoCompartido.lblDescripcion.setText(descripcion);
                    ImpuestoCompartido.importe.setText(importeImpuesto.getText());
                    ImpuestoCompartido.idPeriodo.setText(idPeriodo.getText());
                    ImpuestoCompartido.nroCuota=nroCuota;
                    ImpuestoCompartido.bandera=0;
                    impcom.setLocationRelativeTo(null);
                    impcom.setVisible(true); 
                    dispose();  
                }   
            }
            if(r==1){
                JOptionPane.showMessageDialog(new JDialog(),"Agregado Correctamente");
                importeImpuesto.setText(" ");
                comboImpuestos.removeAllItems();
            }
            }catch(NumberFormatException ex){

                JOptionPane.showMessageDialog(new JDialog(),"Inserte un Valor");

            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void importeImpuestoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_importeImpuestoKeyTyped

        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
         if(!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar()!='.'){
            evt.consume();
        }
        if(evt.getKeyChar()=='.' && importeImpuesto.getText().contains(".")){
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_importeImpuestoKeyTyped

    private void comboImpuestosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboImpuestosMouseClicked
   
        
        // TODO add your handling code here:
    }//GEN-LAST:event_comboImpuestosMouseClicked

    private void comboImpuestosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboImpuestosItemStateChanged
    
// TODO add your handling code here:
    }//GEN-LAST:event_comboImpuestosItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarImpuestoCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarImpuestoCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarImpuestoCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarImpuestoCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarImpuestoCuota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboImpuestos;
    public static javax.swing.JLabel idPeriodo;
    private javax.swing.JTextField importeImpuesto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCom;
    // End of variables declaration//GEN-END:variables

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Imagenes/SM.png"));
        return retValue;
    }
    private int idImpuesto;
    public static int nroCuota;
    public static Contrato datosContrato;
     private int idCon;
    private int partida;
    private int periodo;
     
    
}

