/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import conexion.Conexion;
import entidades.Contrato;
import entidades.CuotaImpuesto;
import entidades.Cuotas;
import entidades.Impuesto;
import gestores.GestoresContrato;
import gestores.GestoresImpuestos;
import gestores.fechas;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static pantallas.ImpuestoCompartido.lblIdImpuestoCompartido;
import static pantallas.LiquidacionInquilino.lblPeriodo;

/**
 *
 * @author Nahuel
 */
public class AgregarImpuestoCodBarra extends javax.swing.JFrame {

    /**
     * Creates new form AgregarImpuestos
     */
    public AgregarImpuestoCodBarra() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCom = new javax.swing.JLabel();
        ingresar = new javax.swing.JButton();
        codBarra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblIdCon = new javax.swing.JLabel();
        lblPeriodo = new javax.swing.JLabel();
        lblImpuesto = new javax.swing.JLabel();
        lblImporte = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Impuesto");
        setIconImage(getIconImage());
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jButton1.setText("Finalizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Impuesto: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Importe:");

        jLabel5.setText("$");

        lblCom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ingresar.setText("Ingresar");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });

        codBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codBarraActionPerformed(evt);
            }
        });
        codBarra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codBarraKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Id Contrato:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Codigo de Barra: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Periodo:");

        lblIdCon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblPeriodo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblImpuesto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblImporte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblCom, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1))
                                    .addComponent(ingresar, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblIdCon)
                                                .addGap(124, 124, 124)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPeriodo)
                                            .addComponent(lblImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(codBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresar))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lblIdCon)
                        .addComponent(lblPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(lblImporte)
                    .addComponent(jLabel1)
                    .addComponent(lblImpuesto))
                .addGap(22, 22, 22)
                .addComponent(lblCom)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        
        String descripcion= lblImpuesto.getText();
            try{
            int r=0;  
            String sql2="SELECT * FROM `impuesto`ORDER BY idImpuesto DESC LIMIT 1";
            ResultSet rs2=null;
            try{
                PreparedStatement pst2=Conexion.getConexionn().prepareStatement(sql2);
                rs2=pst2.executeQuery();            
                while(rs2.next()){
                     idImpuesto=Integer.parseInt(rs2.getString("idImpuesto"))+1;
                }
            }catch (SQLException e) {
                JOptionPane.showMessageDialog(new JDialog(),"Error al consultar Impuesto"+e.toString());
            }
            Contrato contrato=new Contrato();
            Cuotas cuotas=new Cuotas();
            CuotaImpuesto cuotaImp=new CuotaImpuesto();
            Impuesto impuesto=new Impuesto();

            contrato.setIdContrato(idCon);
            cuotas.setContrato(contrato);
            cuotas.setNroCuota(nroCuota);        

            impuesto.setIdImpuesto(idImpuesto);
            impuesto.setIdDescripcion(idDesc);
            impuesto.setValor(Double.parseDouble(lblImporte.getText()));

            cuotaImp.setCuotas(cuotas);
            cuotaImp.setImpuesto(impuesto);

            try {
                lblCom.setText(GestoresImpuestos.TraerImpuestoCompartido(idCon, idDesc));
            } catch (SQLException ex) {
                Logger.getLogger(DetallesContrato.class.getName()).log(Level.SEVERE, null, ex);
            }    
            if(lblCom.getText().isEmpty()){
                GestoresImpuestos gestorImp=new GestoresImpuestos();
                GestoresContrato gestorCon=new GestoresContrato();
                r=gestorImp.GestorAltaImpuesto(cuotaImp);
                try {
                    int rr=gestorImp.ActualizarTotalImpuesto(idCon, nroCuota);

                    int actualizarTotal=gestorCon.ActualizarTotalaPagar(idCon, nroCuota);
                } catch (SQLException ex) {
                    Logger.getLogger(AgregarImpuestoCodBarra.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                Object[] opciones = {"Cargar impuesto compartido", "Cancelar"};
                int eleccion = JOptionPane.showOptionDialog(null, "El impuesto "+ descripcion+ " es compartido","Mensaje de Confirmacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE, null, opciones, "Cancelar");
                if (eleccion == JOptionPane.YES_OPTION) {
                    int x=GestoresImpuestos.ultimoIdImpuestoCompartido()+1;
                    String idImp= Integer.toString(x);
                    ImpuestoCompartido impcom = new ImpuestoCompartido();
                    ImpuestoCompartido.lblDescripcion.setText(descripcion);
                    ImpuestoCompartido.importe.setText(lblImporte.getText());
//                    ImpuestoCompartido.idPeriodo.setText(idPeriodo.getText());
                    ImpuestoCompartido.nroCuota=nroCuota;
                    impcom.setLocationRelativeTo(null);
                    impcom.setVisible(true); 
                    dispose();  
                }   
            }
            if(r==1){
                JOptionPane.showMessageDialog(new JDialog(),"Agregado Correctamente");
            }
            }catch(NumberFormatException ex){

                JOptionPane.showMessageDialog(new JDialog(),"Inserte un Valor");

            }
//        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        GestoresImpuestos gestorImp=new GestoresImpuestos();
        try {
            String cb = (codBarra.getText());
            int n=(codBarra.getText().length());
            switch(n){
                case 50://API                    
                    partida = (cb.substring(8,25));
                    periodo = (codBarra.getText().substring(33, 39)); 

                    idCon=gestorImp.consultaIdPorTitular(partida,13);                   
                    datosContrato=GestoresContrato.consultaDatosContrato(Integer.parseInt(String.valueOf(idCon)));
                    inicio = (datosContrato.getFechaInicio());
                    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");       
                    String fechaInicio = inicio;
                    String actual = periodo.substring(4,6)+"/"+periodo.substring(2,4)+"/"+"20"+periodo.substring(0,2); 
                    Date fechaInicial=dateFormat.parse(fechaInicio);
                    Date fechaFinal=dateFormat.parse(actual);
                    int cantmes = fechas.calcularMesesAFecha(fechaInicial ,fechaFinal );
                    datosCuotas = gestorCon.consultarCuotaLiquidacion(idCon,cantmes );
                    totalPagar = (datosCuotas.getTotalaPagar());
                    lblIdCon.setText(String.valueOf(idCon));
                    lblPeriodo.setText(actual);
                    String sql="SELECT * FROM `descripcionimpuesto` WHERE idDescripcion = 13";
                    ResultSet rs=null;
                    try{
                        PreparedStatement pst=Conexion.getConexionn().prepareStatement(sql);
                        rs=pst.executeQuery();
                    while(rs.next()){
                        lblImpuesto.setText(rs.getString("descripcion"));
                    }
                    int cb2 = Integer.parseInt(cb.substring(40,49));                  
                    int tam= (String.valueOf(cb2).length());
                    String cb3=String.valueOf(cb2);
                    lblImporte.setText(cb3.substring(0,tam-2)+","+cb3.substring(tam-2,tam));
            
        }catch (SQLException e) {
			JOptionPane.showMessageDialog(new JDialog(),"Error al consultar Impuesto"+e.toString());
        }
                    
                break;            
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(new JDialog(),"Inserte un Valor");
        
           }catch (ParseException ex) {
            Logger.getLogger(ImpuestoCompartido.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarActionPerformed

    private void codBarraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codBarraKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_codBarraKeyTyped

    private void codBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codBarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codBarraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarImpuestoCodBarra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarImpuestoCodBarra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarImpuestoCodBarra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarImpuestoCodBarra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarImpuestoCodBarra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codBarra;
    private javax.swing.JButton ingresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblCom;
    private javax.swing.JLabel lblIdCon;
    private javax.swing.JLabel lblImporte;
    private javax.swing.JLabel lblImpuesto;
    private javax.swing.JLabel lblPeriodo;
    // End of variables declaration//GEN-END:variables

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Imagenes/SM.png"));
        return retValue;
    }
    private int idImpuesto;
    public static int nroCuota;
    public static Contrato datosContrato;
    private int idCon;
    private String partida;
    private String periodo;
    private int idDesc;
    private int cuota;
    private String inicio;
    public static Cuotas datosCuotas;
    GestoresContrato gestorCon=new GestoresContrato();
    public static double totalPagar;
     
    
}

