/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import Renders.RenderEliminarImpuesto;
import Renders.RenderEliminarImpuestoCompartido;
import conexion.Conexion;
import entidades.Contrato;
import entidades.CuotaImpuesto;
import entidades.Cuotas;
import entidades.Impuesto;
import gestores.GestoresContrato;
import gestores.GestoresImpuestos;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import modelos.ModeloTablaImpuesto;
import modelos.ModeloTablaImpuestoCompartido;
import static pantallas.AgregarImpuestoCuota.idPeriodo;
import static pantallas.AgregarImpuestoCuota.nroCuota;
import static pantallas.DetallesContrato.tablaImpuestos;

/**
 *
 * @author Nahuel
 */
public class CargaImpuestoCompartido extends javax.swing.JFrame {

    /**
     * Creates new form AgregarImpuestos
     */
    public CargaImpuestoCompartido() {
        initComponents();
        this.setResizable(false);
    }
int idic;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboImpuestos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        porcentajeImpuesto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarInmueble = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInmuebles = new javax.swing.JTable();
        btnAgregarInmueble = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblInmueble = new javax.swing.JTextField();
        lblIdImpuestoCompartido = new javax.swing.JLabel();
        lblIdContrato = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Impuesto");
        setIconImage(getIconImage());
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jButton1.setText("Finalizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Impuesto: ");

        comboImpuestos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Porcentaje:");

        porcentajeImpuesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                porcentajeImpuestoKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Agregar Inmueble:");

        btnBuscarInmueble.setText("...");
        btnBuscarInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarInmuebleActionPerformed(evt);
            }
        });

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inmuebles Agregados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        tablaInmuebles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaInmuebles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaInmueblesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaInmuebles);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
        );

        btnAgregarInmueble.setText("Agregar");
        btnAgregarInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarInmuebleActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Numero Impuesto Compartido:");

        lblInmueble.setEnabled(false);
        lblInmueble.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblInmuebleKeyTyped(evt);
            }
        });

        lblIdImpuestoCompartido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblIdContrato.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(lblIdContrato)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIdImpuestoCompartido))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAgregarInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(porcentajeImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comboImpuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnBuscarInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(28, 28, 28)
                                            .addComponent(lblInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblIdImpuestoCompartido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIdContrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboImpuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnBuscarInmueble)
                    .addComponent(lblInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(porcentajeImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarInmueble)
                .addGap(49, 49, 49)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        String sql="SELECT * FROM `descripcionimpuesto` ORDER BY `idDescripcion` ASC";
        ResultSet rs=null;
        try{
            PreparedStatement pst=Conexion.getConexionn().prepareStatement(sql);
            rs=pst.executeQuery();
            
            while(rs.next()){
                comboImpuestos.addItem(rs.getString("idDescripcion")+" - "+rs.getString("descripcion"));
            }
            
            
        }catch (SQLException e) {
			JOptionPane.showMessageDialog(new JDialog(),"Error al consultar Impuesto"+e.toString());
        }
        int idImpuestoCompartido= Integer.parseInt(lblIdImpuestoCompartido.getText()); 
            ArrayList<Impuesto> impuestos=GestoresImpuestos.consultaTablaImpuestoCompartido(idImpuestoCompartido);
            ModeloTablaImpuestoCompartido modelo=new ModeloTablaImpuestoCompartido(impuestos);
            tablaInmuebles.setModel(modelo);   
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double totalPorcentaje=0;
        
        int aa= tablaInmuebles.getRowCount();
        if(tablaInmuebles.getRowCount()<1){
            JOptionPane.showMessageDialog(new JDialog(),"Debe cargar dos o mas inmuebles");
        }else{
            for(int i=0; i<tablaInmuebles.getRowCount();i++){
                String porcentaje=tablaInmuebles.getValueAt(i,1).toString();
                totalPorcentaje=totalPorcentaje+Double.parseDouble(porcentaje); 
            }
            if(totalPorcentaje == 100){ 
            dispose(); 
            
            }else{
                JOptionPane.showMessageDialog(new JDialog(),"El total de los porcentajes debe ser igual a 100");
            }
        }
     
            

        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void porcentajeImpuestoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_porcentajeImpuestoKeyTyped

        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
         if(!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar()!='.'){
            evt.consume();
        }
        if(evt.getKeyChar()=='.' && porcentajeImpuesto.getText().contains(".")){
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_porcentajeImpuestoKeyTyped

    private void btnBuscarInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarInmuebleActionPerformed

    ListaContratos pantallacontratos= new ListaContratos();
    pantallacontratos.pack();
    pantallacontratos.setLocationRelativeTo(null);
    pantallacontratos.setVisible(true);
    // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarInmuebleActionPerformed

    private void btnAgregarInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarInmuebleActionPerformed
    String descripcion=(String) comboImpuestos.getSelectedItem();
    try {
        int idcon=Integer.parseInt(lblIdContrato.getText());
        int idDesc = (Integer.parseInt(descripcion.substring(0,(descripcion.indexOf("-")-1))));
        idCom = (GestoresImpuestos.TraerImpuestoCompartido( idcon,idDesc ));
    } catch (Exception exc) {

    }
    if(idCom.isEmpty()){
        
        try{

            int idImpuestoCompartido= Integer.parseInt(lblIdImpuestoCompartido.getText()); 

            Contrato contrato=new Contrato();
            Cuotas cuotas=new Cuotas();
            CuotaImpuesto cuotaImp=new CuotaImpuesto();
            Impuesto impuesto=new Impuesto();

    //            contrato.setIdContrato(Integer.parseInt(idPeriodo.getText().substring(0, idPeriodo.getText().indexOf("-")-1)));

            cuotas.setContrato(contrato);
            cuotas.setNroCuota(nroCuota);        

            impuesto.setIdDescripcion(Integer.parseInt(descripcion.substring(0,(descripcion.indexOf("-")-1))));
            impuesto.setPorcentaje(Double.parseDouble(porcentajeImpuesto.getText()));
            impuesto.setIdImpuestoCompartido(Integer.parseInt(lblIdImpuestoCompartido.getText()));

            cuotaImp.setCuotas(cuotas);
            cuotaImp.setImpuesto(impuesto);


            GestoresImpuestos gestorImp=new GestoresImpuestos();


            int rrr=gestorImp.GestorAltaImpuestoCompartido(cuotaImp, Integer.parseInt(lblIdContrato.getText()) );




            JOptionPane.showMessageDialog(new JDialog(),"Agregado Correctamente");
            porcentajeImpuesto.setText(" ");
            lblIdContrato.setText(" ");
            lblInmueble.setText(" ");
            comboImpuestos.addItem(descripcion);  
            comboImpuestos.setEnabled(false);
            ArrayList<Impuesto> impuestos=GestoresImpuestos.consultaTablaImpuestoCompartido(idImpuestoCompartido);
            ModeloTablaImpuestoCompartido modelo=new ModeloTablaImpuestoCompartido(impuestos);
//            tablaInmuebles.setDefaultRenderer(Object.class, new RenderEliminarImpuestoCompartido());
            tablaInmuebles.setModel(modelo);

        }catch(NumberFormatException ex){

            JOptionPane.showMessageDialog(new JDialog(),"Inserte un Valor");
         
        }
      
    }else{
           JOptionPane.showMessageDialog(new JDialog(),"Ya se cargo un impuesto compartido con este impuesto y este contrato");
            porcentajeImpuesto.setText(" ");
            lblIdContrato.setText(" ");
            lblInmueble.setText(" ");

    }
 
        
    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarInmuebleActionPerformed

    private void lblInmuebleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblInmuebleKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_lblInmuebleKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

         int x=GestoresImpuestos.ultimoIdImpuestoCompartido()+1;
         String idImp= Integer.toString(x);
//         lblIdImpuestoCompartido.setText(idImp);
//         idic= Integer.parseInt(lblIdImpuestoCompartido.getText());
        
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void tablaInmueblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaInmueblesMouseClicked

         if(evt.getClickCount()==2){
 
            int idImpuestoCompartido= Integer.parseInt(lblIdImpuestoCompartido.getText()); 

    

            Object[] opciones = {"Aceptar", "Cancelar"};
            int eleccion = JOptionPane.showOptionDialog(null, "¿Desea limpiar la lista de impuestos compartidos?", "Mensaje de Confirmacion",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE, null, opciones, "Cancelar");
            if (eleccion == JOptionPane.YES_OPTION) {

                try{
                    int r=GestoresImpuestos.EliminarImpuestoCompartido(idImpuestoCompartido);

                    if(r==1){

                        ArrayList<Impuesto> impuestos=GestoresImpuestos.consultaTablaImpuestoCompartido(idImpuestoCompartido);
                        ModeloTablaImpuestoCompartido modelo=new ModeloTablaImpuestoCompartido(impuestos);
                        tablaInmuebles.setModel(modelo);
                        comboImpuestos.setEnabled(true);
                        
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(CargaImpuestoCompartido.class.getName()).log(Level.SEVERE, null, ex);
                }
  
            }

        }        // TODO add your handling code here:
    }//GEN-LAST:event_tablaInmueblesMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    int idImpuestoCompartido= Integer.parseInt(lblIdImpuestoCompartido.getText());

    try{
        int r=GestoresImpuestos.EliminarImpuestoCompartido(idImpuestoCompartido);
     
    } catch (SQLException ex) {
        Logger.getLogger(CargaImpuestoCompartido.class.getName()).log(Level.SEVERE, null, ex);
    }   
  
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargaImpuestoCompartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargaImpuestoCompartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargaImpuestoCompartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargaImpuestoCompartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargaImpuestoCompartido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarInmueble;
    private javax.swing.JButton btnBuscarInmueble;
    private javax.swing.JComboBox<String> comboImpuestos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblIdContrato;
    public static javax.swing.JLabel lblIdImpuestoCompartido;
    public static javax.swing.JTextField lblInmueble;
    private javax.swing.JTextField porcentajeImpuesto;
    public static javax.swing.JTable tablaInmuebles;
    // End of variables declaration//GEN-END:variables

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Imagenes/Cagliero.png"));
        return retValue;
    }
    private int idImpuesto;
    public static int nroCuota;
    public static String idCom;
    private boolean fin= false;
}

